# full model_config_path: ../TinySPOS/configs/{model_config_path}/quant_dmtp_single.yml
model_config_path: 'toy_dmtp_config_/level_'

func_path: 'inference/Core/Src/quantization_inference.c' 
data_path: 'inference/Core/Inc/data.h'

# full tensor path: ../TinySPOS/{tensor_path}
tensor_path: 'tensor/'

# full memory_list path: ../TinySPOS/{memory_list}
memory_list: 'statistic.yml'

func_init: 'init/func_init.txt'
data_init: 'init/data_init.txt'

# ram section size for calculation
ram_size: 300