# full model_config_path: ../TinySPOS/configs/{model_config_path}/quant_dmtp_single.yml
model_config_path: 'toy_dmtp_config_/level_'

# input image info
image_path: 'input/3.npy'
image_class: 3

# count of [downsample, mv2block, transformer]
# assert dmt_count = 1 or dmt_count = 2
dmt_count: 2

# block size
block: 2

# force_sparse == False: tensors are sparse if sparse encoding reduce the size
# force_sparse == true: all tensors are sparse
force_sparse: True


# constant part
# full tensor path: ../TinySPOS/{tensor_path}
tensor_path: 'tensor/'

# full memory_list path: ../TinySPOS/{memory_list}
memory_list: 'statistic.yml'

func_path: 'inference/Core/Src/quantization_inference.c' 
data_path: 'inference/Core/Inc/data.h'
func_init: 'init/func_init.txt'
data_init: 'init/data_init.txt'